const sampleProducts = [
    {name: "Rinso Cair", category: "Kebersihan", quantity: 10, capital: 1000, price: 2000, imgUrl:""},
    {name: "Sabun Lifeboy Batang", category:"Kebersihan", quantity:20, capital:3700, price:4500, imgUrl:"/images/lifeboy.jpg"},
    {name: "Sunlight", category:"Kebersihan", quantity:15, capital:4300, price:5000, imgUrl:"/images/sunlight.jpg"},
    {name: "Pasta Gigi Pepsodent 75gr", category:"Kebersihan", quantity:10, capital:5100, price:6500, imgUrl:"/images/pepsodent.jpg"},
    {name: "Shampo Sachet Lifeboy 1 renteng", category:"Kebersihan", quantity:10, capital:5000, price:6000, imgUrl:"/images/sampho.jpg"},
    {name: "So Klin Lantai 25ml", category:"Kebersihan", quantity:15, capital:700,price:1500, imgUrl:"/images/soklin.jpg"}, 
    {name: "Bodrex Flu & Batuk", category:"Kesehatan", quantity:10, capital:2200, price:3000, imgUrl:"/images/bodrex.jpg"},
    {name: "Antangin Cair", category:"Kesehatan", quantity:20, capital:1300, price:2000, imgUrl:"/images/antangin.jpg"},
    {name: "Tetes Mata Insto", category:"Kesehatan", quantity:10, capital:15000, price:18000, imgUrl:"/images/insto.jpg"},
    {name: "Freshcare", category:"Kesehatan", quantity:10, capital:13000, price:15000, imgUrl:"/images/freshcare.jpg"},
    {name: "Diapet", category:"Kesehatan", quantity:10, capital:2500, price:4000, imgUrl:"/images/diapet.jpg"},
    {name: "Roma Biskuit Kelapa", category:"Cemilan", quantity:15, capital:4500, price:6000, imgUrl:"/images/roma.jpg"},
    {name: "Chitato (Small Pack 68g)", category:"Cemilan", quantity:10, capital:7000, price:9500, imgUrl:"/images/chitato.jpg"},
    {name: "Taro Net (Small Pack 60gr)", category:"Cemilan", quantity:12, capital:5000, price:7000, imgUrl:"/images/taro.jpg"},
    {name: "Beng-Beng", category:"Cemilan", quantity:20, capital:1800, price:2500, imgUrl:"/images/bengbeng.jpg"},
    {name: "Nextar Brownies (1pcs)", category:"Cemilan", quantity:18, capital:2000, price:3000, imgUrl:"/images/nextar.jpg"},
    {name: "Parfum Vitalis Men 100ml", category:"Gaya Hidup", quantity:8, capital:28000, price:42000, imgUrl:"/images/parfum.jpg"},
    {name: "Rexona Deodorant Roll On 50ml", category:"Gaya Hidup", quantity:12, capital:15000, price:22000, imgUrl:"/images/rexona.jpg"},
    {name: "Kaca Mata Hitam", category:"Gaya Hidup", quantity:10, capital:15000, price:20000, imgUrl:"/images/kacamata.jpg"},
    {name: "Flatshoes", category:"Gaya Hidup", quantity:5, capital:80000, price:10000, imgUrl:"/images/flatshoes.jpg"},
    {name: "Hoodie", category:"Gaya Hidup", quantity:10, capital:75000, price:85000, imgUrl:"/images/hoodie.jpg"},
]
export default sampleProducts